# Dockerfile
FROM python:3.9

WORKDIR /code

COPY ./proyectoFinal/requirements_api.txt .

RUN pip install --no-cache-dir --upgrade -r requirements_api.txt

# Copiar todos los archivos de tu aplicación en el directorio actual al /code en el contenedor
COPY ./proyectoFinal/*.py /code

# El comando para ejecutar la aplicación con Uvicorn. Ajusta la ruta del módulo si es necesario.
CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--reload"]

