# Usar una imagen base oficial de Python
FROM python:3.9

# Configurar el directorio de trabajo
WORKDIR /app

# Copiar los archivos requeridos al contenedor
COPY ./proyectoFinal/requirements_streamlit.txt ./
COPY ./proyectoFinal/app_streamlit.py ./

# Instalar las dependencias
RUN pip install -r requirements_streamlit.txt

# Exponer el puerto que Streamlit utiliza por defecto
EXPOSE 8501

# Comando para ejecutar la aplicación Streamlit
CMD ["streamlit", "run", "app_streamlit.py", "--server.port=8501", "--server.address=0.0.0.0"]
