version: '1'

services:
  jupiter-project1:
    container_name: tfx
    image: "tensorflow/tfx:1.12.0"
    build:
      network: host
    ports: 
      - "8888:8888"
      - "6006:6006"
    volumes:
          - '.:/tfx/src'
    entrypoint: /run_jupyter.sh
    stdin_open: true # docker run -i
    tty: true        # docker run -t
