
services:
  
  miapi:
    build:
#      context: .
       dockerfile: Dockerfile_api
    #image: "anloder4/proyecto2-mi_api:latest"
    volumes:
      - ./app:/code/app
    ports:
      - "8085:8000"
    #depends_on:
    #- mlflow_serv
    #- minio
    environment:
      MLFLOW_URI: "http://10.43.101.156:8084"
      MLFLOW_S3_ENDPOINT_URL: http://10.43.101.156:31000
      AWS_ACCESS_KEY_ID: admin
      AWS_SECRET_ACCESS_KEY: supersecret
    deploy:
      resources:
        limits:
          cpus: "2"
          memory: 500M


volumes:
  mysql_data:
  notebooks:
networks:
  network1:
      name: proyecto31_default
      external: true
