apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose-api.yaml
    kompose.version: 1.33.0 (3ce457399)
  labels:
    io.kompose.service: mysql
  name: mysql
spec:
  type: NodePort
  ports:
    - name: "8082"
      port: 8082
      targetPort: 3306
      nodePort: 30082
  selector:
    io.kompose.service: mysql
